---

zabbix_proxy_gab:
  ip: ""
  name: ""

zabbix_proxy_dp:
  ip: ""
  name: ""

zabbix_server_active: "{{ lookup('vars', 'zabbix_proxy_' + zabbix_proxy_dc) }}"
  
zabbix_psk_id: "PSK ID {{ ansible_facts['fqdn'] }}"
